export const SET_CURRENT_MONTH_NAME = 'SET_CURRENT_MONTH_NAME';
export const SET_CURRENT_MONTH = 'SET_CURRENT_MONTH';
export const SET_CURRENT_YEAR = 'SET_CURRENT_YEAR';
export const SET_TITLE = 'SET_TITLE';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_IS_RECURRING = 'SET_IS_RECURRING';
export const SET_IS_ENDING = 'SET_IS_ENDING';
export const SET_IS_CUSTOM = 'SET_IS_CUSTOM';
export const SET_EXPENSE_DATE = 'SET_EXPENSE_DATE';
export const SET_MONTHLY_DATE = 'SET_MONTHLY_DATE';
export const SET_DATA_LOADED = "SET_DATA_LOADED";
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const CLEAR_FIELDS = 'CLEAR_FIELDS';
export const SELECT_FREQUENCY = 'SELECT_FREQUENCY';
export const SET_YEARLY_MONTH = 'SET_YEARLY_MONTH';
export const SET_SELECTED_YEAR = 'SET_SELECTED_YEAR';
export const ADD_PAID_MONTH = 'ADD_PAID_MONTH';
export const REMOVE_PAID_MONTH = 'REMOVE_PAID_MONTH';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const SET_FILTERED_EXPENSES = 'SET_FILTERED_EXPENSES';
export const GET_EXPENSES = 'GET_EXPENSES';
export const SET_EXPENSEDOC_ID = 'SET_EXPENSEDOC_ID';

//Users Actions Types

export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_USER_ID = 'SET_USER_ID';


export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

// App Action Types

export const TOGGLE_THEME_COLORS = 'TOGGLE_THEME_COLORS';

// Device action types

export const UPDATE_DEVICE_TOKEN = 'UPDATE_DEVICE_TOKEN';
